name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ghidra_version:
        description: 'Specify the Ghidra version(s) you want to build for (e.g. "latest", "11.2")'
        required: true
        default: '"11.2"'
  schedule:
    - cron: '0 0 1 * *' # Monthly

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ghidra: ${{ fromJSON(format('[{0}]', inputs.ghidra_version || '"latest","11.2"')) }}

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    
    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Install Ghidra ${{ matrix.ghidra }}
      uses: antoniovazquezblanco/setup-ghidra@v2.0.4
      with:
        auth_token: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ matrix.ghidra }}

    - name: Build
      working-directory: ${{ github.workspace }}/XEXLoaderWV
      run: |
        gradle buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: XEXLoaderWV_Ghidra_${{ matrix.ghidra }}
        path: XEXLoaderWV/dist/*.zip
